# Dockerfile.octane
FROM php:8.4-cli

# 👷 Instale dependências básicas
RUN apt-get update && apt-get install -y \
    git \
    unzip \
    libpng-dev \
    libonig-dev \
    libxml2-dev \
    libzip-dev \
    libjpeg-dev \
    libfreetype6-dev \
    && apt-get clean

# 🔧 Instale extensões necessárias
RUN docker-php-ext-configure gd --with-freetype --with-jpeg && \
    docker-php-ext-install \
    pdo_mysql \
    mbstring \
    bcmath \
    gd \
    sockets \
    zip \
    pcntl

# 🌀 Instale Swoole para Octane
RUN pecl install swoole && docker-php-ext-enable swoole

# 🎼 Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

WORKDIR /var/www
COPY . .

# ⚙️ Starta o Octane
CMD ["php", "artisan", "octane:start", "--server=swoole", "--host=0.0.0.0", "--port=8000"]
